#throw placeholderapi errors into console instead of hiding them
throw-placeholderapi-exceptions: false
#forward chat messages to TAB-Additions on the proxy
chat: false
#msg when placeholders aren't loaded yet
placeholders-loading-msg: "Loading..."