name: TAB-Bridge
version: ${project.version}
author: NEZNAMY
main: me.neznamy.tab.bridge.bukkit.BukkitBridge
api-version: 1.13
website: "https://www.mc-market.org/resources/21641/"
softdepend: [PlaceholderAPI, Vault, Essentials]
description: "Extends features when TAB is installed on BungeeCord"